### ISSUE TITLE
Umbrella issue to for adding LICENSE files

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew-index#341]
This is an umbrella issue to track which plugins still need to include a license file in their archive. These licenses need to be added upstream in the plugin repositories.

Also see #310 and https://docs.google.com/spreadsheets/d/1Q3enNf61muuVQw6eWLsMTfZJ67tbEpedKAH94MjbBjI/edit?usp=sharing for further details.

- [ ] [passman](https://github.com/chrisns/kubectl-passman) -- tracking PR https://github.com/chrisns/kubectl-passman/issues/36
- [ ] [get-all](https://github.com/corneliusweig/ketall) -- tracking PR https://github.com/corneliusweig/ketall/issues/30
- [ ] [debug-shell](https://github.com/danisla/kubefunc) -- tracking PR https://github.com/danisla/kubefunc/issues/5
- [ ] [gke-credentials](https://github.com/danisla/kubefunc) -- tracking PR https://github.com/danisla/kubefunc/issues/5
- [ ] [node-admin](https://github.com/danisla/kubefunc) -- tracking PR https://github.com/danisla/kubefunc/issues/5
- [ ] [pod-logs](https://github.com/danisla/kubefunc) -- tracking PR https://github.com/danisla/kubefunc/issues/5
- [ ] [pod-shell](https://github.com/danisla/kubefunc) -- tracking PR https://github.com/danisla/kubefunc/issues/5
- [ ] [sniff](https://github.com/eldadru/ksniff) -- tracking PR https://github.com/eldadru/ksniff/issues/50
- [ ] [doctor](https://github.com/emirozer/kubectl-doctor) -- tracking PR https://github.com/emirozer/kubectl-doctor/issues/7
- [ ] [view-utilization](https://github.com/etopeter/kubectl-view-utilization) -- tracking PR https://github.com/etopeter/kubectl-view-utilization/issues/51
- [ ] [match-name](https://github.com/gerald1248/kubectl-match-name) -- tracking PR https://github.com/gerald1248/kubectl-match-name/issues/1
- [ ] [grep](https://github.com/guessi/kubectl-grep) -- tracking PR https://github.com/guessi/kubectl-grep/issues/16
- [x] [auth-proxy](https://github.com/int128/kauthproxy) -- tracking PR https://github.com/int128/kauthproxy/issues/29
- [x] [oidc-login](https://github.com/int128/kubelogin) -- tracking PR https://github.com/int128/kubelogin/issues/188
- [ ] [neat](https://github.com/itaysk/kubectl-neat) -- tracking PR https://github.com/itaysk/kubectl-neat/issues/21
- [ ] [rbac-view](https://github.com/jasonrichardsmith/rbac-view) -- tracking PR https://github.com/jasonrichardsmith/rbac-view/issues/23
- [ ] [exec-as](https://github.com/jordanwilson230/kubectl-plugins/tree/krew#kubectl-exec-as) -- tracking PR https://github.com/jordanwilson230/kubectl-plugins/issues/16
- [ ] [prompt](https://github.com/jordanwilson230/kubectl-plugins/tree/krew#kubectl-prompt) -- tracking PR https://github.com/jordanwilson230/kubectl-plugins/issues/16
- [ ] [change-ns](https://github.com/juanvallejo/kubectl-ns) -- tracking PR https://github.com/juanvallejo/kubectl-ns/issues/3
- [ ] [eksporter](https://github.com/Kyrremann/kubectl-eksporter) -- tracking PR https://github.com/Kyrremann/kubectl-eksporter/issues/2
- [ ] [evict-pod](https://github.com/rajatjindal/kubectl-evict-pod) -- tracking PR https://github.com/rajatjindal/kubectl-evict-pod/issues/2
- [ ] [modify-secret](https://github.com/rajatjindal/kubectl-modify-secret) -- tracking PR https://github.com/rajatjindal/kubectl-modify-secret/issues/6
- [ ] [whoami](https://github.com/rajatjindal/kubectl-whoami) -- tracking PR https://github.com/rajatjindal/kubectl-whoami/issues/2
- [ ] [fields](https://github.com/rewanth1997/kubectl-fields) -- tracking PR https://github.com/rewanth1997/kubectl-fields/issues/1
- [ ] [kubesec-scan](https://github.com/stefanprodan/kubectl-kubesec) -- tracking PR https://github.com/controlplaneio/kubectl-kubesec/issues/22
- [ ] [mtail](https://gitlab.com/grzesuav/kubectl-mtail) -- tracking PR https://gitlab.com/grzesuav/kubectl-mtail/issues/6
- [ ] [ingress-nginx](https://kubernetes.github.io/ingress-nginx/kubectl-plugin/) -- tracking PR https://github.com/kubernetes/ingress-nginx/issues/4755
- [ ] [virt](https://kubevirt.io) -- tracking PR https://github.com/dhiller/kubectl-virt-plugin/issues/9

/priority important-soon

**Comment by jordanwilson230** [comment]
@corneliusweig https://github.com/kubernetes-sigs/krew-index/pull/348 takes care of the ```exec-as``` and ```prompt``` plugins.
